import 'semantic-ui-css/semantic.min.css'
import './MainPage'
import './CourseList'
import './LoginButton'
import './LogoutButton'
import './LikeButton'
import './CategoryTab'
import './MyPageTab'
import './ReviewForm'

